# -*- coding: utf-8 -*-
"""L06_Graded_Task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sVncxrtHObuIbjtX6BVOgC3_wE6nLz3Y

Read Data from excercise.csv
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

MYdata = pd.read_csv("exercise1.csv")

"""Choose Dependent and Independent Variables"""

X = MYdata[['Visitors', 'AvgTemp']]
y = MYdata['ParkingTkts']

"""Split Your datatset into 1:2 partition"""

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

"""Train your Regression Model on Training Dataset"""

model = LinearRegression()
model.fit(X_train, y_train)

"""Test your Model using Testing Data Set"""

y_predict = model.predict(X_test)

"""Implement Evaluation Metrices"""

MSE = mean_squared_error(y_test, y_predict)
r2 = r2_score(y_test, y_predict)
print("Mean Squared Error:", MSE)
print("R squared:", r2)

"""Draw Graph of Predicted and Actual Dependent Values  vs Independent Values"""

plt.scatter(X_test['Visitors'], y_test, color='black', label='Actual')
plt.scatter(X_test['Visitors'], y_predict, color='blue', label='Predicted')
plt.xlabel('Visitors')
plt.ylabel('Parking Tickets')
plt.title('Actual vs Predicted Parking Tickets')
plt.legend()
plt.show()

